
exclude: '^(\.|_|output/?|livedata/?|tmp/?|logs/?|interactive/?).*$'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.4'
    hooks:
    -   id: flake8
        exclude: '^(\.|_|output/?|livedata/?|tmp/?|logs/?|processing/?).*$'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.780'
    hooks:
    -   id: mypy
        additional_dependencies:
        -   'pydantic==1.5.1'

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.28.0'
    hooks:
    -   id: yapf
        args: ['--diff']

# 'isort' checking has issues...

# It runs from within its own virtualenv so it cannot properly
# detect 3rd-party libraries, which messes up ordering.

# seed-isort-config tries to solve this, but requires updating
# isort's config file each run, and

# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v2.1.1
#     hooks:
#     -   id: seed-isort-config

# -   repo: https://github.com/timothycrosley/isort
#     rev: '4.3.21'
#     hooks:
#     -   id: isort
#         args: ['--check-only','--recursive']

